// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbNHgL-7w-4AIcNyASimgW4trPPWJ-Vhk',
    appId: '1:227901589859:web:5f576fd99d47856868ab56',
    messagingSenderId: '227901589859',
    projectId: 'chat-app-71c92',
    authDomain: 'chat-app-71c92.firebaseapp.com',
    storageBucket: 'chat-app-71c92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsVAgSloMp78n1d449R02fheVSVkm0u0',
    appId: '1:227901589859:android:8eb477b9a0507c0468ab56',
    messagingSenderId: '227901589859',
    projectId: 'chat-app-71c92',
    storageBucket: 'chat-app-71c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHsp0_3d_YdRLXPzq87-JJRpGecJVtRg',
    appId: '1:227901589859:ios:e91a5d004a5ceb7a68ab56',
    messagingSenderId: '227901589859',
    projectId: 'chat-app-71c92',
    storageBucket: 'chat-app-71c92.firebasestorage.app',
    iosBundleId: 'com.example.ssMusicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcHsp0_3d_YdRLXPzq87-JJRpGecJVtRg',
    appId: '1:227901589859:ios:e91a5d004a5ceb7a68ab56',
    messagingSenderId: '227901589859',
    projectId: 'chat-app-71c92',
    storageBucket: 'chat-app-71c92.firebasestorage.app',
    iosBundleId: 'com.example.ssMusicplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbNHgL-7w-4AIcNyASimgW4trPPWJ-Vhk',
    appId: '1:227901589859:web:98c9310eb7cbf7ff68ab56',
    messagingSenderId: '227901589859',
    projectId: 'chat-app-71c92',
    authDomain: 'chat-app-71c92.firebaseapp.com',
    storageBucket: 'chat-app-71c92.firebasestorage.app',
  );
}
